### ISSUE TITLE
Any idea how to launch this on docker where is no php executable?

### ISSUE THREAD

**Issue by vytenis-sciukas-nfq** [sensiolabs/StorybookBundle#49]
=> Failed to build the preview
Error: Symfony console failed with exit status 127:
CMD: 'php' 'bin/console' 'debug:container' '--parameter=kernel.project_dir' '--format=json' '-v'
Output: 
Error output: /bin/sh: 1: php: not found

Seems like php executable is hardcoded and there is no way to launch this properly on docker. I was unable to find information on docs how to resolve this, but this is a major blocker.

**Comment by jon-ht** [comment]
Hi, unfortunatly it's not possible

I'm working on a rework of internal JS commands to not depend on PHP binary here https://github.com/sensiolabs/StorybookBundle/pull/47

This is still a draft, as I am waiting for maintainers to accept this solution.

In the meantime, you would have to download PHP on your machine, or use your own Storybook setup

**Comment by stu-ad** [comment]
After a fair bit of fighting, I was able to get this working with our Dockerized app.  It's far from perfect, performance isn't great but it does work.  I am running Storybook on the same container as the Symfony application and exposing the port in docker-compose.yml - This is obviously tailored to our setup with Traefik but hopeful someone finds this helpful as a starter.  With the below setup I can access the Storybook manager at localhost:6006 running against my app exposed on dev-server.test

I've tried to just include the relevant parts below:

```yaml
php:
        image: ghcr.io/our-private-image-with-node-installed
        container_name: php83
        volumes:
            - ~/local-dirs:/volumes/exposed/from-container
        ports:
            - "3000:3000"  // exposed to access pentatrion vite bundle dev server
            - "6006:6006" // exposed to access storybook
        networks:
            - traefik
reverse-proxy:
        image: traefik:v2.9.8
        container_name: traefik
        networks:
            traefik:
                aliases:
                    - "dev-server.test"
```

In the storybook main.ts file.

```typescript
const config: StorybookConfig = {
    stories: ['../stories/**/*.stories.[tj]s', '../stories/**/*.mdx'],
    addons: [
        '@storybook/addon-essentials',
    ],
    framework: {
        name: '@sensiolabs/storybook-symfony-webpack5',
        options: {
            symfony: {
                server: 'dev-server.test',
                proxyPaths: ['/images', '/assets', '/_components', '/Fonts', '/dist', '/css'],
                additionalWatchPaths: [
                    'assets',
                ]
            }
        },
    },
    docs: {
        autodocs: 'tag',
    },
}
```

We have a little python helper to make it more convenient to run but essentially we ssh into the php container and run the following from the app route directory:

```
npx storybook dev -p 6006 -h 0.0.0.0 --no-open --disable-telemetry --config-dir .storybook
```
